name: Build OpenWrt (Use macOS)

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  watch:
    types: [started]

jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: Initialization environment
      run: |
        brew cask install docker
        sudo systemsetup -settimezone "Asia/Shanghai"
        
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
